/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files\mingw64-6.3.0\mingw64\bin\gcc.exe" -c  -w -mno-ms-bitfields  -IC:\nim-0.18.0\lib -o C:\Roguelike\src\fontprocs\nimcache\fontloader.o C:\Roguelike\src\fontprocs\nimcache\fontloader.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA;
typedef struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_Xo4YhcsfLAmbGDNu1Obfcw tyTuple_Xo4YhcsfLAmbGDNu1Obfcw;
typedef struct tyObject_FontPtrcolonObjectType__aRlNW02x3t1nWe9bTYP3kng tyObject_FontPtrcolonObjectType__aRlNW02x3t1nWe9bTYP3kng;
typedef struct tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w;
typedef struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct tyTuple_mqgjJG1vbS44JnBjm1SPfQ tyTuple_mqgjJG1vbS44JnBjm1SPfQ;
typedef struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg tyObject_PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg;
typedef struct tyObject_BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g tyObject_BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g;
typedef struct tyObject_Palette_D3H7z9cPmFr0tk2z8jKdcYg tyObject_Palette_D3H7z9cPmFr0tk2z8jKdcYg;
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA {
NI fontSideLength;
NI startingAsciiNum;
NI numColumns;
NI numRows;
NI texPtrWidth;
NI texPtrHeight;
tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* fontTexPtr;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple_Xo4YhcsfLAmbGDNu1Obfcw {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
typedef N_CDECL_PTR(tyObject_FontPtrcolonObjectType__aRlNW02x3t1nWe9bTYP3kng*, tyProc_BoF4LjRpO6kzulElGXVNAw) (NCSTRING file, int ptsize);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA {
  Exception Sup;
};
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CDECL_PTR(int, tyProc_wKYDDTeVzttM58CI64tPlA) (tyObject_FontPtrcolonObjectType__aRlNW02x3t1nWe9bTYP3kng* font);
typedef N_CDECL_PTR(tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w*, tyProc_jhdVmRFWTpNd1iR9aS9c5hQQ) (int flags, int width, int height, int depth, NU32 Rmask, NU32 Gmask, NU32 BMask, NU32 Amask);
typedef N_CDECL_PTR(tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w*, tyProc_nQ9c9aC2GjqC38nPxZnuKL7w) (tyObject_FontPtrcolonObjectType__aRlNW02x3t1nWe9bTYP3kng* font, NU16 ch, tyTuple_Xo4YhcsfLAmbGDNu1Obfcw fg);
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
typedef N_CDECL_PTR(int, tyProc_La2eHmSFhImpZ84Uve4Uvw) (tyObject_FontPtrcolonObjectType__aRlNW02x3t1nWe9bTYP3kng* font, NU16 ch, int* minx, int* maxx, int* miny, int* maxy, int* advance);
typedef NI32 tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_HHjOD3TYfv9cxd3GBEF7zxg) (tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w* src, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* srcrect, tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w* dst, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* dstrect);
typedef N_CDECL_PTR(tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*, tyProc_yiZ9abLEqUROCb9aLBrLOHAQ) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w* surface);
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_wbFMpEnGfJo5HTFBx413GA) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* srcrect, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* dstrect);
struct tyTuple_mqgjJG1vbS44JnBjm1SPfQ {
tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* Field0;
tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* Field1;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_CDECL_PTR(int, tyProc_zHpDbFN4o9bvP9cAphXAUHXg) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, tyProc_9a8AalbnAaIxTUMpzQQqpjw) (tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, tyProc_CGFSM2Hc7U0HyNmEEh3xng) (NU32 ms);
struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg {
char dummy;
};
struct tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw {
char dummy;
};
struct tyObject_FontPtrcolonObjectType__aRlNW02x3t1nWe9bTYP3kng {
char dummy;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w {
NU32 flags;
tyObject_PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg* format;
NI32 w;
NI32 h;
NI32 pitch;
void* pixels;
void* userdata;
NI32 locked;
void* lock_data;
tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ clip_rect;
tyObject_BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g* map;
int refcount;
};
struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w {
char dummy;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
typedef NU8 tyArray_bN9bddWn8oiNSHn2MqEJSZQ[2];
struct tyObject_PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg {
NU32 format;
tyObject_Palette_D3H7z9cPmFr0tk2z8jKdcYg* palette;
NU8 BitsPerPixel;
NU8 BytesPerPixel;
tyArray_bN9bddWn8oiNSHn2MqEJSZQ padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
tyObject_PixelFormat_xqbq9cabb4AcV4cRzuGg5Dg* next;
};
struct tyObject_BlitMapPtrcolonObjectType__uPOUAQyskDVXmxvDq3Wk3g {
char dummy;
};
struct tyObject_Palette_D3H7z9cPmFr0tk2z8jKdcYg {
int ncolors;
tyTuple_Xo4YhcsfLAmbGDNu1Obfcw* colors;
NU32 version;
int refcount;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, generateTextureDimensions_napV2kc9bCChuVHx8ngTSWg)(NI totalChars, NI rectSide);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQfontloader)(NI* x, NI y);
N_LIB_PRIVATE N_NIMCALL(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA*, sizedTTFToBitMap_FLQzUa0NzVA7RNcRwciW7Q)(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NimStringDesc* fontFile, int fontSize, NI asciiStartCharNum, NI asciiEndCharNum);
static N_NIMCALL(void, Marker_tyRef_vtq4RNlb4PMmDKIIv5ITIA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_CDECL(tyTuple_Xo4YhcsfLAmbGDNu1Obfcw, color_q7CCTpZMpqm0tLIu9aALLzQ)(NI r, NI g, NI b, NI a);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, blitSurface_gA5THwgl5IwlISePxVZBoQfontloader)(tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w* src, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* srcrect, tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w* dst, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* dstrect);
N_LIB_PRIVATE N_NIMCALL(void, renderChar_DUR9aMPj8fGuVv59bPdKQnKQ)(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA* font, NI x, NI y, NIM_CHAR character);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_LIB_PRIVATE N_NIMCALL(void, renderChar_9aMLSe4D0v5gjigtI4CkNbw)(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA* font, NI x, NI y, NI charIndex);
N_LIB_PRIVATE N_NIMCALL(tyTuple_mqgjJG1vbS44JnBjm1SPfQ, initRenderer_jR75rxYI0iTrnhwMM7JB7A)(int screenWidth, int screenHeight);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_kK9bcPyRB6aksL3Wcn9a0I9bw_37)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_ttfInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_ttfDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_errorhandlingInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_errorhandlingDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_initrendererInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_initrendererDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, fontloaderDatInit000)(void);
NU32 rMask_WpYzeyUa8Be1hxCP5KVcJw;
NU32 gMask_9ctEui2rBXD5O4o87L6yf0g;
NU32 bMask_FdSAAhCQMKpaJz3LCMdBDA;
NU32 aMask_lnDtpTITddpgNmXCZ6lOpQ;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_gTZ4u9bJIuTtQwhK56gCMBA_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_X6TOzpP8PAev43Vu8HltPQ_;
TNimType NTI_vtq4RNlb4PMmDKIIv5ITIA_;
extern tyProc_BoF4LjRpO6kzulElGXVNAw Dl_149613_;
extern TNimType NTI_cogGoQVdHoYneQiFNLztxQ_;
extern TNimType NTI_pdGlehQiZtmAoj9apqLqmvA_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_147654_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_wKYDDTeVzttM58CI64tPlA Dl_149665_;
extern tyProc_jhdVmRFWTpNd1iR9aS9c5hQQ Dl_147048_;
extern tyProc_nQ9c9aC2GjqC38nPxZnuKL7w Dl_149819_;
extern tyProc_La2eHmSFhImpZ84Uve4Uvw Dl_149700_;
extern tyProc_HHjOD3TYfv9cxd3GBEF7zxg Dl_147202_;
extern tyProc_yiZ9abLEqUROCb9aLBrLOHAQ Dl_146833_;
extern tyProc_wbFMpEnGfJo5HTFBx413GA Dl_146988_;
tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window_v8NUo3N68kt4afJZySdBtA;
tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer_HL1h1ZvThzjL49aWp16z5yA;
tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA* testFont_onE7EFHM9aXrZm8ht4RbFng;
extern tyProc_zHpDbFN4o9bvP9cAphXAUHXg Dl_147017_;
tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ rect_tRxauEvurKs9apWQKIMG9bwQ;
extern tyProc_9a8AalbnAaIxTUMpzQQqpjw Dl_147036_;
extern tyProc_CGFSM2Hc7U0HyNmEEh3xng Dl_147403_;
STRING_LITERAL(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_8, "error!", 6);
STRING_LITERAL(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_9, ", SDL error: ", 13);
STRING_LITERAL(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_11, "even here\?!", 11);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_kK9bcPyRB6aksL3Wcn9a0I9bw_10 = {((NimStringDesc*) &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_11)}
;
STRING_LITERAL(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_19, "wtf!!", 5);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_kK9bcPyRB6aksL3Wcn9a0I9bw_18 = {((NimStringDesc*) &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_19)}
;
STRING_LITERAL(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_24, "here too!", 9);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_kK9bcPyRB6aksL3Wcn9a0I9bw_23 = {((NimStringDesc*) &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_24)}
;
STRING_LITERAL(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_38, "../../assets/fonts/OxygenMono-Regular.ttf", 41);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_kK9bcPyRB6aksL3Wcn9a0I9bw_39 = {((NimStringDesc*) &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_8)}
;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3498, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQfontloader)(NI* x, NI y) {
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_3;
	nimfr_("*=", "system.nim");
	nimln_(3695, "system.nim");
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_3 = mulInt((*x), y);
	(*x) = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_3);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, generateTextureDimensions_napV2kc9bCChuVHx8ngTSWg)(NI totalChars, NI rectSide) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	NI texWidth;
	NI texHeight;
	nimfr_("generateTextureDimensions", "fontloader.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(40, "fontloader.nim");
	texWidth = ((NI) 2);
	nimln_(41, "fontloader.nim");
	texHeight = ((NI) 2);
	{
		nimln_(43, "fontloader.nim");
		while (1) {
			NI numCharsPerRow;
			NI numRows;
			NF T3_;
			NF T4_;
			NF T10_;
			NF T11_;
			numCharsPerRow = (NI)0;
			numRows = (NI)0;
			nimln_(47, "fontloader.nim");
			T3_ = (NF)0;
			T3_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(texWidth, rectSide);
			numCharsPerRow = ((NI) (T3_));
			nimln_(48, "fontloader.nim");
			T4_ = (NF)0;
			T4_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(texHeight, rectSide);
			numRows = ((NI) (T4_));
			nimln_(49, "fontloader.nim");
			{
				NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_2;
				TM_kK9bcPyRB6aksL3Wcn9a0I9bw_2 = mulInt(numCharsPerRow, numRows);
				if (!(totalChars <= (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_2))) goto LA7_;
				nimln_(50, "fontloader.nim");
				goto LA1;
			}
			goto LA5_;
			LA7_: ;
			{
				nimln_(52, "fontloader.nim");
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQfontloader((&texWidth), ((NI) 2));
			}
			LA5_: ;
			nimln_(53, "fontloader.nim");
			T10_ = (NF)0;
			T10_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(texWidth, rectSide);
			numCharsPerRow = ((NI) (T10_));
			nimln_(54, "fontloader.nim");
			T11_ = (NF)0;
			T11_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(texHeight, rectSide);
			numRows = ((NI) (T11_));
			nimln_(55, "fontloader.nim");
			{
				NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_4;
				TM_kK9bcPyRB6aksL3Wcn9a0I9bw_4 = mulInt(numCharsPerRow, numRows);
				if (!(totalChars <= (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_4))) goto LA14_;
				nimln_(56, "fontloader.nim");
				goto LA1;
			}
			goto LA12_;
			LA14_: ;
			{
				nimln_(58, "fontloader.nim");
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQfontloader((&texHeight), ((NI) 2));
			}
			LA12_: ;
		}
	} LA1: ;
	nimln_(60, "fontloader.nim");
	result.Field0 = texWidth;
	result.Field1 = texHeight;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_vtq4RNlb4PMmDKIIv5ITIA)(void* p, NI op) {
	tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA* a;
	a = (tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA*)p;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, blitSurface_gA5THwgl5IwlISePxVZBoQfontloader)(tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w* src, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* srcrect, tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w* dst, tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ* dstrect) {
	tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw result;
	nimfr_("blitSurface", "sdl2.nim");
	result = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
	nimln_(1749, "sdl2.nim");
	result = Dl_147202_(src, srcrect, dst, dstrect);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA*, sizedTTFToBitMap_FLQzUa0NzVA7RNcRwciW7Q)(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NimStringDesc* fontFile, int fontSize, NI asciiStartCharNum, NI asciiEndCharNum) {
	tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA* result;
	tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA* T1_;
	tyTuple_Xo4YhcsfLAmbGDNu1Obfcw whiteColour;
	NI totalChars;
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_6;
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_7;
	tyObject_FontPtrcolonObjectType__aRlNW02x3t1nWe9bTYP3kng* font;
	int rectSides;
	NI textureWidth;
	NI textureHeight;
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ _;
	tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w* compositeSurface;
	NF T9_;
	NF T10_;
	NI i;
	tyObject_TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* fontTexPtr;
	nimfr_("sizedTTFToBitMap", "fontloader.nim");
{	result = (tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA*)0;
	nimln_(64, "fontloader.nim");
	T1_ = (tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA*)0;
	T1_ = (tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA*) newObj((&NTI_vtq4RNlb4PMmDKIIv5ITIA_), sizeof(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA));
	result = T1_;
	nimln_(65, "fontloader.nim");
	(*result).startingAsciiNum = asciiStartCharNum;
	nimln_(68, "fontloader.nim");
	whiteColour = color_q7CCTpZMpqm0tLIu9aALLzQ(((NI) 255), ((NI) 255), ((NI) 255), ((NI) 255));
	nimln_(69, "fontloader.nim");
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_6 = subInt(asciiEndCharNum, asciiStartCharNum);
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_7 = addInt((NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_6), ((NI) 1));
	totalChars = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_7);
	nimln_(71, "fontloader.nim");
	font = Dl_149613_(fontFile->data, fontSize);
	nimln_(72, "fontloader.nim");
	{
		tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA* e;
		NimStringDesc* T6_;
		NCSTRING T7_;
		NimStringDesc* T8_;
		if (!(font == 0)) goto LA4_;
		e = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*) newObj((&NTI_cogGoQVdHoYneQiFNLztxQ_), sizeof(tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA));
		(*e).Sup.Sup.m_type = (&NTI_pdGlehQiZtmAoj9apqLqmvA_);
		nimln_(72, "fontloader.nim");
		T6_ = (NimStringDesc*)0;
		nimln_(10, "errorhandling.nim");
		T7_ = (NCSTRING)0;
		T7_ = Dl_147654_();
		T8_ = (NimStringDesc*)0;
		T8_ = cstrToNimstr(T7_);
		T6_ = rawNewString(((NimStringDesc*) &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_8)->Sup.len + T8_->Sup.len + 13);
appendString(T6_, ((NimStringDesc*) &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_8));
appendString(T6_, ((NimStringDesc*) &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_9));
appendString(T6_, T8_);
		asgnRefNoCycle((void**) (&(*e).Sup.message), T6_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(10, "errorhandling.nim");
		raiseException((Exception*)e, "SDLException");
	}
	LA4_: ;
	nimln_(76, "fontloader.nim");
	rectSides = Dl_149665_(font);
	textureWidth = (NI)0;
	textureHeight = (NI)0;
	nimln_(82, "fontloader.nim");
	_ = generateTextureDimensions_napV2kc9bCChuVHx8ngTSWg(totalChars, ((NI) (rectSides)));
	textureWidth = _.Field0;
	textureHeight = _.Field1;
	nimln_(84, "fontloader.nim");
	compositeSurface = Dl_147048_(((int) 0), ((int)chckRange(textureWidth, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(textureHeight, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int) 32), rMask_WpYzeyUa8Be1hxCP5KVcJw, gMask_9ctEui2rBXD5O4o87L6yf0g, bMask_FdSAAhCQMKpaJz3LCMdBDA, aMask_lnDtpTITddpgNmXCZ6lOpQ);
	nimln_(86, "fontloader.nim");
	T9_ = (NF)0;
	T9_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(textureWidth, ((NI) (rectSides)));
	(*result).numColumns = ((NI) (T9_));
	nimln_(87, "fontloader.nim");
	T10_ = (NF)0;
	T10_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(textureHeight, ((NI) (rectSides)));
	(*result).numRows = ((NI) (T10_));
	nimln_(88, "fontloader.nim");
	(*result).texPtrWidth = textureWidth;
	nimln_(89, "fontloader.nim");
	(*result).texPtrHeight = textureHeight;
	nimln_(92, "fontloader.nim");
	i = asciiStartCharNum;
	{
		NI y;
		NI colontmp_;
		NI i_2;
		y = (NI)0;
		colontmp_ = (NI)0;
		nimln_(93, "fontloader.nim");
		colontmp_ = (*result).numRows;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_22;
				if (!(i_2 < colontmp_)) goto LA13;
				nimln_(3521, "system.nim");
				y = i_2;
				{
					NI x;
					NI colontmp__2;
					NI i_3;
					x = (NI)0;
					colontmp__2 = (NI)0;
					nimln_(94, "fontloader.nim");
					colontmp__2 = (*result).numColumns;
					nimln_(3519, "system.nim");
					i_3 = ((NI) 0);
					{
						nimln_(3520, "system.nim");
						while (1) {
							NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_21;
							if (!(i_3 < colontmp__2)) goto LA16;
							nimln_(3521, "system.nim");
							x = i_3;
							nimln_(95, "fontloader.nim");
							{
								tyObject_Surface_sOGmuBWrSv9c4mZ0oaW1R1w* textSurface;
								int minX;
								int maxX;
								int minY;
								int maxY;
								int advance;
								tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ dstRect;
								int T25_;
								NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_17;
								tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T35_;
								NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_20;
								if (!(i <= asciiEndCharNum)) goto LA19_;
								nimln_(96, "fontloader.nim");
								textSurface = Dl_149819_(font, ((NU16) (i)), whiteColour);
								nimln_(97, "fontloader.nim");
								{
									if (!(textSurface == 0)) goto LA23_;
									nimln_(98, "fontloader.nim");
									echoBinSafe(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_10, 1);
								}
								LA23_: ;
								minX = (int)0;
								maxX = (int)0;
								minY = (int)0;
								maxY = (int)0;
								advance = (int)0;
								memset((void*)(&dstRect), 0, sizeof(dstRect));
								nimln_(109, "fontloader.nim");
								T25_ = (int)0;
								T25_ = Dl_149700_(font, ((NU16) (i)), (&minX), (&maxX), (&minY), (&maxY), (&advance));
								T25_;
								nimln_(110, "fontloader.nim");
								{
									NIM_BOOL T28_;
									NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_12;
									T28_ = (NIM_BOOL)0;
									T28_ = (minX == ((NI32) 0));
									if (!(T28_)) goto LA29_;
									T28_ = (maxX == ((NI32) 0));
									LA29_: ;
									if (!T28_) goto LA30_;
									nimln_(111, "fontloader.nim");
									TM_kK9bcPyRB6aksL3Wcn9a0I9bw_12 = mulInt(x, ((NI) (rectSides)));
									dstRect.Field0 = ((int)chckRange((NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_12), ((int) (-2147483647 -1)), ((int) 2147483647)));
								}
								goto LA26_;
								LA30_: ;
								{
									NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_13;
									NF T33_;
									NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_14;
									NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_15;
									NF T34_;
									NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_16;
									nimln_(113, "fontloader.nim");
									TM_kK9bcPyRB6aksL3Wcn9a0I9bw_13 = mulInt(x, ((NI) (rectSides)));
									T33_ = (NF)0;
									T33_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(((NI) (rectSides)), ((NI) 2));
									TM_kK9bcPyRB6aksL3Wcn9a0I9bw_14 = addInt((NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_13), ((NI) (T33_)));
									TM_kK9bcPyRB6aksL3Wcn9a0I9bw_15 = addInt(minX, maxX);
									if (TM_kK9bcPyRB6aksL3Wcn9a0I9bw_15 < (-2147483647 -1) || TM_kK9bcPyRB6aksL3Wcn9a0I9bw_15 > 2147483647) raiseOverflow();
									T34_ = (NF)0;
									T34_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(((NI) ((NI32)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_15))), ((NI) 2));
									TM_kK9bcPyRB6aksL3Wcn9a0I9bw_16 = subInt((NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_14), ((NI) (T34_)));
									dstRect.Field0 = ((int)chckRange((NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_16), ((int) (-2147483647 -1)), ((int) 2147483647)));
								}
								LA26_: ;
								nimln_(114, "fontloader.nim");
								TM_kK9bcPyRB6aksL3Wcn9a0I9bw_17 = mulInt(y, ((NI) (rectSides)));
								dstRect.Field1 = ((int)chckRange((NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_17), ((int) (-2147483647 -1)), ((int) 2147483647)));
								nimln_(115, "fontloader.nim");
								dstRect.Field2 = rectSides;
								nimln_(116, "fontloader.nim");
								dstRect.Field3 = rectSides;
								nimln_(117, "fontloader.nim");
								T35_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
								T35_ = blitSurface_gA5THwgl5IwlISePxVZBoQfontloader(textSurface, NIM_NIL, compositeSurface, (&dstRect));
								nimln_(118, "fontloader.nim");
								{
									if (!(compositeSurface == 0)) goto LA38_;
									nimln_(119, "fontloader.nim");
									echoBinSafe(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_18, 1);
								}
								LA38_: ;
								nimln_(122, "fontloader.nim");
								TM_kK9bcPyRB6aksL3Wcn9a0I9bw_20 = addInt(i, ((NI) 1));
								i = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_20);
							}
							goto LA17_;
							LA19_: ;
							{
								nimln_(124, "fontloader.nim");
								goto LA14;
							}
							LA17_: ;
							nimln_(3522, "system.nim");
							TM_kK9bcPyRB6aksL3Wcn9a0I9bw_21 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_21);
						} LA16: ;
					}
				} LA14: ;
				nimln_(125, "fontloader.nim");
				{
					if (!(asciiEndCharNum < i)) goto LA43_;
					nimln_(126, "fontloader.nim");
					goto LA11;
				}
				LA43_: ;
				nimln_(3522, "system.nim");
				TM_kK9bcPyRB6aksL3Wcn9a0I9bw_22 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_22);
			} LA13: ;
		}
	} LA11: ;
	nimln_(130, "fontloader.nim");
	fontTexPtr = Dl_146833_(renderer, compositeSurface);
	nimln_(131, "fontloader.nim");
	{
		if (!(fontTexPtr == 0)) goto LA47_;
		nimln_(132, "fontloader.nim");
		echoBinSafe(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_23, 1);
	}
	LA47_: ;
	nimln_(133, "fontloader.nim");
	(*result).fontTexPtr = fontTexPtr;
	nimln_(134, "fontloader.nim");
	(*result).fontSideLength = ((NI) (rectSides));
	nimln_(135, "fontloader.nim");
	(*result).startingAsciiNum = asciiStartCharNum;
	nimln_(136, "fontloader.nim");
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, renderChar_DUR9aMPj8fGuVv59bPdKQnKQ)(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA* font, NI x, NI y, NIM_CHAR character) {
	NI column;
	NI charNum;
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_25;
	NI row;
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_26;
	NI xPos;
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_29;
	NI yPos;
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_30;
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ srcRect;
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ dstRect;
	tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T6_;
	nimfr_("renderChar", "fontloader.nim");
	column = (NI)0;
	nimln_(143, "fontloader.nim");
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_25 = subInt(((NI) (((NU8)(character)))), (*font).startingAsciiNum);
	charNum = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_25);
	nimln_(144, "fontloader.nim");
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_26 = divInt(charNum, (*font).numColumns);
	row = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_26);
	nimln_(145, "fontloader.nim");
	{
		NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_27;
		NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_28;
		if (!((*font).numColumns < charNum)) goto LA3_;
		nimln_(146, "fontloader.nim");
		TM_kK9bcPyRB6aksL3Wcn9a0I9bw_27 = mulInt(row, (*font).numColumns);
		TM_kK9bcPyRB6aksL3Wcn9a0I9bw_28 = subInt(charNum, (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_27));
		column = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_28);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(148, "fontloader.nim");
		column = charNum;
	}
	LA1_: ;
	nimln_(151, "fontloader.nim");
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_29 = mulInt(column, (*font).fontSideLength);
	xPos = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_29);
	nimln_(152, "fontloader.nim");
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_30 = mulInt(row, (*font).fontSideLength);
	yPos = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_30);
	memset((void*)(&srcRect), 0, sizeof(srcRect));
	nimln_(155, "fontloader.nim");
	srcRect.Field0 = ((int)chckRange(xPos, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(156, "fontloader.nim");
	srcRect.Field1 = ((int)chckRange(yPos, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(157, "fontloader.nim");
	srcRect.Field2 = ((int)chckRange((*font).fontSideLength, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(158, "fontloader.nim");
	srcRect.Field3 = ((int)chckRange((*font).fontSideLength, ((int) (-2147483647 -1)), ((int) 2147483647)));
	memset((void*)(&dstRect), 0, sizeof(dstRect));
	nimln_(161, "fontloader.nim");
	dstRect.Field0 = ((int)chckRange(x, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(162, "fontloader.nim");
	dstRect.Field1 = ((int)chckRange(y, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(163, "fontloader.nim");
	dstRect.Field2 = ((int)chckRange((*font).fontSideLength, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(164, "fontloader.nim");
	dstRect.Field3 = ((int)chckRange((*font).fontSideLength, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(166, "fontloader.nim");
	T6_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
	T6_ = Dl_146988_(renderer, (*font).fontTexPtr, (&srcRect), (&dstRect));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, renderChar_9aMLSe4D0v5gjigtI4CkNbw)(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA* font, NI x, NI y, NI charIndex) {
	NI charNum;
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_31;
	NI column;
	NI row;
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_32;
	NI xPos;
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_35;
	NI yPos;
	NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_36;
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ srcRect;
	tyTuple_Ye8PLO8qqXk1tek2VP9c0UQ dstRect;
	tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T6_;
	nimfr_("renderChar", "fontloader.nim");
	nimln_(169, "fontloader.nim");
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_31 = subInt(charIndex, (*font).startingAsciiNum);
	charNum = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_31);
	column = (NI)0;
	nimln_(173, "fontloader.nim");
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_32 = divInt(charNum, (*font).numColumns);
	row = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_32);
	nimln_(174, "fontloader.nim");
	{
		NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_33;
		NI TM_kK9bcPyRB6aksL3Wcn9a0I9bw_34;
		if (!((*font).numColumns < charNum)) goto LA3_;
		nimln_(175, "fontloader.nim");
		TM_kK9bcPyRB6aksL3Wcn9a0I9bw_33 = mulInt(row, (*font).numColumns);
		TM_kK9bcPyRB6aksL3Wcn9a0I9bw_34 = subInt(charNum, (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_33));
		column = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_34);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(177, "fontloader.nim");
		column = charNum;
	}
	LA1_: ;
	nimln_(180, "fontloader.nim");
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_35 = mulInt(column, (*font).fontSideLength);
	xPos = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_35);
	nimln_(181, "fontloader.nim");
	TM_kK9bcPyRB6aksL3Wcn9a0I9bw_36 = mulInt(row, (*font).fontSideLength);
	yPos = (NI)(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_36);
	memset((void*)(&srcRect), 0, sizeof(srcRect));
	nimln_(184, "fontloader.nim");
	srcRect.Field0 = ((int)chckRange(xPos, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(185, "fontloader.nim");
	srcRect.Field1 = ((int)chckRange(yPos, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(186, "fontloader.nim");
	srcRect.Field2 = ((int)chckRange((*font).fontSideLength, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(187, "fontloader.nim");
	srcRect.Field3 = ((int)chckRange((*font).fontSideLength, ((int) (-2147483647 -1)), ((int) 2147483647)));
	memset((void*)(&dstRect), 0, sizeof(dstRect));
	nimln_(190, "fontloader.nim");
	dstRect.Field0 = ((int)chckRange(x, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(191, "fontloader.nim");
	dstRect.Field1 = ((int)chckRange(y, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(192, "fontloader.nim");
	dstRect.Field2 = ((int)chckRange((*font).fontSideLength, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(193, "fontloader.nim");
	dstRect.Field3 = ((int)chckRange((*font).fontSideLength, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(195, "fontloader.nim");
	T6_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
	T6_ = Dl_146988_(renderer, (*font).fontTexPtr, (&srcRect), (&dstRect));
	popFrame();
}
static N_NIMCALL(void, TM_kK9bcPyRB6aksL3Wcn9a0I9bw_37)(void) {
	nimGCvisit((void*)testFont_onE7EFHM9aXrZm8ht4RbFng, 0);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_mathDatInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	sdl2_sdl2DatInit000();
	sdl2_ttfDatInit000();
	sdl2_imageDatInit000();
	unknown_errorhandlingDatInit000();
	unknown_initrendererDatInit000();
	fontloaderDatInit000();
	stdlib_mathInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	stdlib_parseutilsInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	sdl2_sdl2Init000();
	sdl2_ttfInit000();
	sdl2_imageInit000();
	unknown_errorhandlingInit000();
	unknown_initrendererInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyTuple_mqgjJG1vbS44JnBjm1SPfQ T6_;
	int T11_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T12_;
	nimfr_("fontloader", "fontloader.nim");
nimRegisterGlobalMarker(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_37);
	nimln_(26, "fontloader.nim");
	{
		if (!NIM_FALSE) goto LA3_;
		nimln_(27, "fontloader.nim");
		rMask_WpYzeyUa8Be1hxCP5KVcJw = ((NU32) IL64(4278190080));
		nimln_(28, "fontloader.nim");
		gMask_9ctEui2rBXD5O4o87L6yf0g = ((NU32) 16711680);
		nimln_(29, "fontloader.nim");
		bMask_FdSAAhCQMKpaJz3LCMdBDA = ((NU32) 65280);
		nimln_(30, "fontloader.nim");
		aMask_lnDtpTITddpgNmXCZ6lOpQ = ((NU32) 255);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(32, "fontloader.nim");
		rMask_WpYzeyUa8Be1hxCP5KVcJw = ((NU32) 255);
		nimln_(33, "fontloader.nim");
		gMask_9ctEui2rBXD5O4o87L6yf0g = ((NU32) 65280);
		nimln_(34, "fontloader.nim");
		bMask_FdSAAhCQMKpaJz3LCMdBDA = ((NU32) 16711680);
		nimln_(35, "fontloader.nim");
		aMask_lnDtpTITddpgNmXCZ6lOpQ = ((NU32) IL64(4278190080));
	}
	LA1_: ;
	nimln_(200, "fontloader.nim");
	T6_ = initRenderer_jR75rxYI0iTrnhwMM7JB7A(((int) 3000), ((int) 1000));
	window_v8NUo3N68kt4afJZySdBtA = T6_.Field0;
	renderer_HL1h1ZvThzjL49aWp16z5yA = T6_.Field1;
	nimln_(202, "fontloader.nim");
	asgnRefNoCycle((void**) (&testFont_onE7EFHM9aXrZm8ht4RbFng), sizedTTFToBitMap_FLQzUa0NzVA7RNcRwciW7Q(renderer_HL1h1ZvThzjL49aWp16z5yA, ((NimStringDesc*) &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_38), ((int) 18), ((NI) 28), ((NI) 300)));
	nimln_(203, "fontloader.nim");
	{
		if (!((*testFont_onE7EFHM9aXrZm8ht4RbFng).fontTexPtr == 0)) goto LA9_;
		nimln_(204, "fontloader.nim");
		echoBinSafe(TM_kK9bcPyRB6aksL3Wcn9a0I9bw_39, 1);
	}
	LA9_: ;
	nimln_(206, "fontloader.nim");
	T11_ = (int)0;
	T11_ = Dl_147017_(renderer_HL1h1ZvThzjL49aWp16z5yA);
	nimln_(208, "fontloader.nim");
	rect_tRxauEvurKs9apWQKIMG9bwQ.Field0 = ((int) 0);
	nimln_(209, "fontloader.nim");
	rect_tRxauEvurKs9apWQKIMG9bwQ.Field1 = ((int) 0);
	nimln_(210, "fontloader.nim");
	rect_tRxauEvurKs9apWQKIMG9bwQ.Field2 = ((int)chckRange((*testFont_onE7EFHM9aXrZm8ht4RbFng).texPtrWidth, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(211, "fontloader.nim");
	rect_tRxauEvurKs9apWQKIMG9bwQ.Field3 = ((int)chckRange((*testFont_onE7EFHM9aXrZm8ht4RbFng).texPtrHeight, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(213, "fontloader.nim");
	memset((void*)T12_, 0, sizeof(T12_));
	T12_[0] = nimIntToStr((*testFont_onE7EFHM9aXrZm8ht4RbFng).fontSideLength);
	echoBinSafe(T12_, 1);
	nimln_(215, "fontloader.nim");
	renderChar_9aMLSe4D0v5gjigtI4CkNbw(renderer_HL1h1ZvThzjL49aWp16z5yA, testFont_onE7EFHM9aXrZm8ht4RbFng, ((NI) 20), ((NI) 20), ((NI) 55));
	nimln_(229, "fontloader.nim");
	Dl_147036_(renderer_HL1h1ZvThzjL49aWp16z5yA);
	nimln_(231, "fontloader.nim");
	Dl_147403_(((NU32) 1000));
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, fontloaderDatInit000)(void) {
static TNimNode* TM_kK9bcPyRB6aksL3Wcn9a0I9bw_5[7];
static TNimNode TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[8];
NTI_gTZ4u9bJIuTtQwhK56gCMBA_.size = sizeof(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA);
NTI_gTZ4u9bJIuTtQwhK56gCMBA_.kind = 18;
NTI_gTZ4u9bJIuTtQwhK56gCMBA_.base = 0;
NTI_gTZ4u9bJIuTtQwhK56gCMBA_.flags = 3;
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_5[0] = &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[1];
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[1].kind = 1;
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[1].offset = offsetof(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA, fontSideLength);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[1].name = "fontSideLength";
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_5[1] = &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[2];
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[2].kind = 1;
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[2].offset = offsetof(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA, startingAsciiNum);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[2].name = "startingAsciiNum";
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_5[2] = &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[3];
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[3].kind = 1;
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[3].offset = offsetof(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA, numColumns);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[3].name = "numColumns";
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_5[3] = &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[4];
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[4].kind = 1;
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[4].offset = offsetof(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA, numRows);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[4].name = "numRows";
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_5[4] = &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[5];
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[5].kind = 1;
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[5].offset = offsetof(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA, texPtrWidth);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[5].name = "texPtrWidth";
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_5[5] = &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[6];
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[6].kind = 1;
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[6].offset = offsetof(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA, texPtrHeight);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[6].name = "texPtrHeight";
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_5[6] = &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[7];
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[7].kind = 1;
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[7].offset = offsetof(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA, fontTexPtr);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[7].typ = (&NTI_X6TOzpP8PAev43Vu8HltPQ_);
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[7].name = "fontTexPtr";
TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[0].len = 7; TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[0].kind = 2; TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[0].sons = &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_5[0];
NTI_gTZ4u9bJIuTtQwhK56gCMBA_.node = &TM_kK9bcPyRB6aksL3Wcn9a0I9bw_0[0];
NTI_vtq4RNlb4PMmDKIIv5ITIA_.size = sizeof(tyObject_BitmappedFontcolonObjectType__gTZ4u9bJIuTtQwhK56gCMBA*);
NTI_vtq4RNlb4PMmDKIIv5ITIA_.kind = 22;
NTI_vtq4RNlb4PMmDKIIv5ITIA_.base = (&NTI_gTZ4u9bJIuTtQwhK56gCMBA_);
NTI_vtq4RNlb4PMmDKIIv5ITIA_.flags = 2;
NTI_vtq4RNlb4PMmDKIIv5ITIA_.marker = Marker_tyRef_vtq4RNlb4PMmDKIIv5ITIA;
}

