/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files\mingw64-6.3.0\mingw64\bin\gcc.exe" -c  -w -mno-ms-bitfields  -IC:\nim-0.18.0\lib -o C:\Roguelike\src\fontprocs\nimcache\freetype_freetype.o C:\Roguelike\src\fontprocs\nimcache\freetype_freetype.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg;
typedef struct tyObject_FT_Open_Args_KeA2ZKgqvZG3KqhPfRY20A tyObject_FT_Open_Args_KeA2ZKgqvZG3KqhPfRY20A;
typedef struct tyObject_FT_Size_Request_4q6Zvp7B7nY9bfpnISl2B5Q tyObject_FT_Size_Request_4q6Zvp7B7nY9bfpnISl2B5Q;
typedef struct tyObject_FT_Matrix_mh32BjSwMEVbu2RTMOqx8g tyObject_FT_Matrix_mh32BjSwMEVbu2RTMOqx8g;
typedef struct tyObject_FT_Vector_i9a9aJ09a4KEQDShfgPmmdO6w tyObject_FT_Vector_i9a9aJ09a4KEQDShfgPmmdO6w;
typedef struct tyObject_FT_GlyphSlotRec_vgLXoE6EShaOvQTaZaFq2A tyObject_FT_GlyphSlotRec_vgLXoE6EShaOvQTaZaFq2A;
typedef struct tyObject_FT_CharMapRec_fUCOr3S4JERtjeA9bN3UBPA tyObject_FT_CharMapRec_fUCOr3S4JERtjeA9bN3UBPA;
typedef struct tyObject_FT_Bitmap_Size_Ke3V9byajORo5h9csjnc7fcA tyObject_FT_Bitmap_Size_Ke3V9byajORo5h9csjnc7fcA;
typedef struct tyObject_FT_Generic_v2AqYLAPOO9aTPLTC6htbcA tyObject_FT_Generic_v2AqYLAPOO9aTPLTC6htbcA;
typedef struct tyObject_FT_BBox_9aNfQBPm09csJabB3X0LeVag tyObject_FT_BBox_9aNfQBPm09csJabB3X0LeVag;
typedef struct tyObject_FT_SizeRec_D9ak4W3o5YNCTOWTV4eJHzw tyObject_FT_SizeRec_D9ak4W3o5YNCTOWTV4eJHzw;
typedef struct tyObject_FT_MemoryRec_9acjr4Asdsvj3kCIjyU9bcdg tyObject_FT_MemoryRec_9acjr4Asdsvj3kCIjyU9bcdg;
typedef struct tyObject_FT_StreamRec_YKqWjAGvIZ52kiJY0CHw2g tyObject_FT_StreamRec_YKqWjAGvIZ52kiJY0CHw2g;
typedef struct tyObject_FT_ListRec_oojxXavMLkWmnFrvgw8idw tyObject_FT_ListRec_oojxXavMLkWmnFrvgw8idw;
typedef struct tyObject_FT_ListNodeRec_XDnyUdoyiWuZr1TEOohiUg tyObject_FT_ListNodeRec_XDnyUdoyiWuZr1TEOohiUg;
typedef struct tyObject_FT_Parameter_NjsbxXAfepI5sznbwCtdWQ tyObject_FT_Parameter_NjsbxXAfepI5sznbwCtdWQ;
typedef struct tyObject_FT_Glyph_Metrics_YKKQ9cHzhJpUIOfSUaVvk5Q tyObject_FT_Glyph_Metrics_YKKQ9cHzhJpUIOfSUaVvk5Q;
typedef struct tyObject_FT_Bitmap_biFTCw6ujA1IbCx9aHzfaSw tyObject_FT_Bitmap_biFTCw6ujA1IbCx9aHzfaSw;
typedef struct tyObject_FT_Outline_K1vYnZnCz9apBqUWehIzF3w tyObject_FT_Outline_K1vYnZnCz9apBqUWehIzF3w;
typedef struct tyObject_FT_Size_Metrics_Y8MS7Si7fWwPitrZa9a9aMHA tyObject_FT_Size_Metrics_Y8MS7Si7fWwPitrZa9a9aMHA;
typedef union tyObject_FT_StreamDesc_wtXGWW69aSPgQYF9aOB6pwUw tyObject_FT_StreamDesc_wtXGWW69aSPgQYF9aOB6pwUw;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, tyProc_woTsLPew4uEvecZTma85ug) (void** alibrary);
typedef N_CDECL_PTR(int, tyProc_Lgz6NmsDXnHcpuiE4Mnofw) (void* library);
typedef N_CDECL_PTR(int, tyProc_GsMkcMnC2p3jO231u2xjng) (void* library, NCSTRING filepathname, long face_index, tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg** aface);
typedef N_CDECL_PTR(int, tyProc_myr4VYWQzqK31s8tKPHspw) (void* library, NCSTRING file_base, long file_size, long face_index, tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg** aface);
typedef N_CDECL_PTR(int, tyProc_DgtznECvnzCE40vIqSeCWQ) (void* library, tyObject_FT_Open_Args_KeA2ZKgqvZG3KqhPfRY20A* args, long face_index, tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg** aface);
typedef N_CDECL_PTR(int, tyProc_ip1VQmvVZva6M7hk4oS2rQ) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, NCSTRING filepathname);
typedef N_CDECL_PTR(int, tyProc_c2ePrv2WfeGvQJiUXzGj8A) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, tyObject_FT_Open_Args_KeA2ZKgqvZG3KqhPfRY20A* parameters);
typedef N_CDECL_PTR(int, tyProc_5UUS9c6EECHRvPK0JfqOaDA) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face);
typedef N_CDECL_PTR(int, tyProc_Sb9by7rnki9aXHiYgGxvvzoA) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, int strike_index);
typedef N_CDECL_PTR(int, tyProc_vzcEEEjX0QSDl0Hf9azA6og) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, tyObject_FT_Size_Request_4q6Zvp7B7nY9bfpnISl2B5Q* req);
typedef N_CDECL_PTR(int, tyProc_QUVBw9auupGHuj883c8jszw) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, long char_width, long char_height, unsigned int horz_resolution, unsigned int vert_resolution);
typedef N_CDECL_PTR(int, tyProc_Hhh1kJz9aJYAqt9brj9bU8evA) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned int pixel_width, unsigned int pixel_height);
typedef N_CDECL_PTR(int, tyProc_8REO9a9aojbMu9aqLG8MMZTBg) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned int glyph_index, NI32 load_flags);
typedef N_CDECL_PTR(int, tyProc_rXKjZ4cakpursqZhHL65mw) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned long char_code, NI32 load_flags);
typedef N_CDECL_PTR(void, tyProc_43qV9cnGImy2biiipQGux9bg) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, tyObject_FT_Matrix_mh32BjSwMEVbu2RTMOqx8g* matrix, tyObject_FT_Vector_i9a9aJ09a4KEQDShfgPmmdO6w* delta);
typedef NU8 tyEnum_FT_Render_Mode_zO3P0oSmwPRTkSEHvaTJFA;
typedef N_CDECL_PTR(int, tyProc_kdxNLzXijGA7NLYJ8H6EiQ) (tyObject_FT_GlyphSlotRec_vgLXoE6EShaOvQTaZaFq2A* slot, tyEnum_FT_Render_Mode_zO3P0oSmwPRTkSEHvaTJFA render_mode);
typedef N_CDECL_PTR(int, tyProc_qPJah9ccEBN5ljbSXRHZs8w) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned int left_glyph, unsigned int right_glyph, unsigned int kern_mode, tyObject_FT_Vector_i9a9aJ09a4KEQDShfgPmmdO6w* akerning);
typedef N_CDECL_PTR(int, tyProc_KKai835y39cHt9cIAKaDLhbw) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, long point_size, int degree, long* akerning);
typedef N_CDECL_PTR(int, tyProc_8h04sZNlHwU3U2GI9b9blcag) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned int glyph_index, void* buffer, unsigned int buffer_max);
typedef N_CDECL_PTR(NCSTRING, tyProc_Ydtz0DlRkMf9au39ayRgQaGA) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face);
typedef N_CDECL_PTR(int, tyProc_lbtJj0Yy3OoP1cPce4aZXw) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, NU32 encoding);
typedef N_CDECL_PTR(int, tyProc_b8FlAQWiP6TAcQHkSq6FYQ) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, tyObject_FT_CharMapRec_fUCOr3S4JERtjeA9bN3UBPA* charmap);
typedef N_CDECL_PTR(int, tyProc_8z7TGAthLqF8peh9bDvcRdw) (tyObject_FT_CharMapRec_fUCOr3S4JERtjeA9bN3UBPA* charmap);
typedef N_CDECL_PTR(unsigned int, tyProc_SFXrLcuAryQrt53QAxf6CA) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned long charcode);
typedef N_CDECL_PTR(unsigned long, tyProc_9cFdZu4Ulq8Y9c0xmrV59cqYA) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned int* agindex);
typedef N_CDECL_PTR(unsigned long, tyProc_RHggp9bPoWBt2cdsdTrKCww) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned long char_code, unsigned int* agindex);
typedef N_CDECL_PTR(unsigned int, tyProc_qs1D4ja0sYcYByaVwPLMOA) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, char* glyph_name);
typedef N_CDECL_PTR(int, tyProc_kdmzsZNv6G6NyszL5PvnIw) (tyObject_FT_GlyphSlotRec_vgLXoE6EShaOvQTaZaFq2A* glyph, unsigned int sub_index, int* p_index, unsigned int* p_flags, int* p_arg1, int* p_arg2, tyObject_FT_Matrix_mh32BjSwMEVbu2RTMOqx8g* p_transform);
typedef N_CDECL_PTR(unsigned short, tyProc_avUrQuqDb8NsLPqXsLm9b9bg) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face);
typedef N_CDECL_PTR(unsigned int, tyProc_Uib9b9cJuJKumeSvTrk3QENA) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned long charcode, unsigned long variantSelector);
typedef N_CDECL_PTR(int, tyProc_FMXoHUjTcACA49akJeI9cTDw) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned long charcode, unsigned long variantSelector);
typedef N_CDECL_PTR(NU32*, tyProc_6cN6EpZdI0pK10qaMEd68g) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face);
typedef N_CDECL_PTR(NU32*, tyProc_xcaajKr56FFuT3sInJCmQQ) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned long charcode);
typedef N_CDECL_PTR(long, tyProc_fy9aiiWKI4snQj1wug1ju7g) (long a, long b, long c);
typedef N_CDECL_PTR(long, tyProc_MVmF0JW9bMI2YoeSQg5TZcg) (long a, long b);
typedef N_CDECL_PTR(long, tyProc_iNFvlsSD7s5Un23DfeYhYw) (long a);
typedef N_CDECL_PTR(void, tyProc_qVAMpBOv41Bn5QNpCEZcWg) (tyObject_FT_Vector_i9a9aJ09a4KEQDShfgPmmdO6w* vec, tyObject_FT_Matrix_mh32BjSwMEVbu2RTMOqx8g* matrix);
typedef N_CDECL_PTR(void, tyProc_u9c7i818npb3ehaU36NHABQ) (void* library, int* amajor, int* aminor, int* apatch);
typedef N_CDECL_PTR(unsigned char, tyProc_YfiMDY6c7TQNpip0kwcGgw) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face);
typedef N_CDECL_PTR(unsigned char, tyProc_p3Rc9aHD2Ie9bCiqQpayUwuw) (tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned char value);
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* obj);
struct tyObject_FT_Generic_v2AqYLAPOO9aTPLTC6htbcA {
void* data;
tyProc_32w2ZypAyMWuajvi2Jt79cg finalizer;
};
struct tyObject_FT_BBox_9aNfQBPm09csJabB3X0LeVag {
long xMin;
long yMin;
long xMax;
long yMax;
};
struct tyObject_FT_ListRec_oojxXavMLkWmnFrvgw8idw {
tyObject_FT_ListNodeRec_XDnyUdoyiWuZr1TEOohiUg* head;
tyObject_FT_ListNodeRec_XDnyUdoyiWuZr1TEOohiUg* tail;
};
struct tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg {
long num_faces;
long face_index;
long face_flags;
long style_flags;
long num_glyphs;
char* family_name;
char* style_name;
int num_fixed_sizes;
tyObject_FT_Bitmap_Size_Ke3V9byajORo5h9csjnc7fcA* available_sizes;
int num_charmaps;
tyObject_FT_CharMapRec_fUCOr3S4JERtjeA9bN3UBPA** charmaps;
tyObject_FT_Generic_v2AqYLAPOO9aTPLTC6htbcA generic;
tyObject_FT_BBox_9aNfQBPm09csJabB3X0LeVag bbox;
unsigned short units_per_EM;
short ascender;
short descender;
short height;
short max_advance_width;
short max_advance_height;
short underline_position;
short underline_thickness;
tyObject_FT_GlyphSlotRec_vgLXoE6EShaOvQTaZaFq2A* glyph;
tyObject_FT_SizeRec_D9ak4W3o5YNCTOWTV4eJHzw* size;
tyObject_FT_CharMapRec_fUCOr3S4JERtjeA9bN3UBPA* charmap;
void* driver;
tyObject_FT_MemoryRec_9acjr4Asdsvj3kCIjyU9bcdg* memory;
tyObject_FT_StreamRec_YKqWjAGvIZ52kiJY0CHw2g* stream;
tyObject_FT_ListRec_oojxXavMLkWmnFrvgw8idw sizes_list;
tyObject_FT_Generic_v2AqYLAPOO9aTPLTC6htbcA autohint;
void* extensions;
void* internal;
};
struct tyObject_FT_Open_Args_KeA2ZKgqvZG3KqhPfRY20A {
unsigned int flags;
unsigned char* memory_base;
long memory_size;
char* pathname;
tyObject_FT_StreamRec_YKqWjAGvIZ52kiJY0CHw2g* stream;
void* driver;
int num_params;
tyObject_FT_Parameter_NjsbxXAfepI5sznbwCtdWQ* params;
};
typedef NU8 tyEnum_FT_Size_Request_Type_ZNgfNcwY1bP9bPDJ7aM82dw;
struct tyObject_FT_Size_Request_4q6Zvp7B7nY9bfpnISl2B5Q {
tyEnum_FT_Size_Request_Type_ZNgfNcwY1bP9bPDJ7aM82dw typ;
long width;
long height;
unsigned int horiResolution;
unsigned int vertResolution;
};
struct tyObject_FT_Matrix_mh32BjSwMEVbu2RTMOqx8g {
long xx;
long xy;
long yx;
long yy;
};
struct tyObject_FT_Vector_i9a9aJ09a4KEQDShfgPmmdO6w {
long x;
long y;
};
struct tyObject_FT_Glyph_Metrics_YKKQ9cHzhJpUIOfSUaVvk5Q {
long width;
long height;
long horiBearingX;
long horiBearingY;
long horiAdvance;
long vertBearingX;
long vertBearingY;
long vertAdvance;
};
struct tyObject_FT_Bitmap_biFTCw6ujA1IbCx9aHzfaSw {
unsigned int rows;
unsigned int width;
int pitch;
NCSTRING buffer;
unsigned short num_grays;
unsigned char pixel_mode;
unsigned char palette_mode;
void* palette;
};
struct tyObject_FT_Outline_K1vYnZnCz9apBqUWehIzF3w {
short n_contours;
short n_points;
tyObject_FT_Vector_i9a9aJ09a4KEQDShfgPmmdO6w* points;
char* tags;
short* contours;
int flags;
};
struct tyObject_FT_GlyphSlotRec_vgLXoE6EShaOvQTaZaFq2A {
void* library;
tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face;
tyObject_FT_GlyphSlotRec_vgLXoE6EShaOvQTaZaFq2A* next;
unsigned int reserved;
tyObject_FT_Generic_v2AqYLAPOO9aTPLTC6htbcA generic;
tyObject_FT_Glyph_Metrics_YKKQ9cHzhJpUIOfSUaVvk5Q metrics;
long linearHoriAdvance;
long linearVertAdvance;
tyObject_FT_Vector_i9a9aJ09a4KEQDShfgPmmdO6w advance;
unsigned long format;
tyObject_FT_Bitmap_biFTCw6ujA1IbCx9aHzfaSw bitmap;
int bitmap_left;
int bitmap_top;
tyObject_FT_Outline_K1vYnZnCz9apBqUWehIzF3w outline;
unsigned int num_subglyphs;
void* subglyphs;
void* control_data;
long control_len;
long lsb_delta;
long rsb_delta;
void* other;
void* internal;
};
struct tyObject_FT_CharMapRec_fUCOr3S4JERtjeA9bN3UBPA {
tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face;
NU32 encoding;
unsigned short platform_id;
unsigned short encoding_id;
};
struct tyObject_FT_Bitmap_Size_Ke3V9byajORo5h9csjnc7fcA {
short height;
short width;
long size;
long x_ppem;
long y_ppem;
};
struct tyObject_FT_Size_Metrics_Y8MS7Si7fWwPitrZa9a9aMHA {
unsigned short x_ppem;
unsigned short y_ppem;
long x_scale;
long y_scale;
long ascender;
long descender;
long height;
long max_advance;
};
struct tyObject_FT_SizeRec_D9ak4W3o5YNCTOWTV4eJHzw {
tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face;
tyObject_FT_Generic_v2AqYLAPOO9aTPLTC6htbcA generic;
tyObject_FT_Size_Metrics_Y8MS7Si7fWwPitrZa9a9aMHA metrics;
void* internal;
};
typedef N_CDECL_PTR(void*, tyProc_wgUMC2fsYaZrYXeMtANKcg) (tyObject_FT_MemoryRec_9acjr4Asdsvj3kCIjyU9bcdg* memory, long size);
typedef N_CDECL_PTR(void, tyProc_l80Pc1N9b9axuG9bx6RF1Ph3g) (tyObject_FT_MemoryRec_9acjr4Asdsvj3kCIjyU9bcdg* memory, void* block_0);
typedef N_CDECL_PTR(void*, tyProc_ICoyGqQI8V4axG8LJl9cJow) (tyObject_FT_MemoryRec_9acjr4Asdsvj3kCIjyU9bcdg* memory, long cur_size, long new_size, void* block_0);
struct tyObject_FT_MemoryRec_9acjr4Asdsvj3kCIjyU9bcdg {
void* user;
tyProc_wgUMC2fsYaZrYXeMtANKcg alloc;
tyProc_l80Pc1N9b9axuG9bx6RF1Ph3g free;
tyProc_ICoyGqQI8V4axG8LJl9cJow realloc;
};
union tyObject_FT_StreamDesc_wtXGWW69aSPgQYF9aOB6pwUw {
long value;
void* pointer;
};
typedef N_CDECL_PTR(unsigned long, tyProc_H6nliDJVM2eRhxqIhm04fw) (tyObject_FT_StreamRec_YKqWjAGvIZ52kiJY0CHw2g* stream, unsigned long offset, NCSTRING buffer, unsigned long count);
typedef N_CDECL_PTR(void, tyProc_FVZyQJwqE24TPCD764qojQ) (tyObject_FT_StreamRec_YKqWjAGvIZ52kiJY0CHw2g* stream);
struct tyObject_FT_StreamRec_YKqWjAGvIZ52kiJY0CHw2g {
NCSTRING base;
unsigned long size;
unsigned long pos;
tyObject_FT_StreamDesc_wtXGWW69aSPgQYF9aOB6pwUw descriptor;
tyObject_FT_StreamDesc_wtXGWW69aSPgQYF9aOB6pwUw pathname;
tyProc_H6nliDJVM2eRhxqIhm04fw read;
tyProc_FVZyQJwqE24TPCD764qojQ close;
tyObject_FT_MemoryRec_9acjr4Asdsvj3kCIjyU9bcdg* memory;
NCSTRING cursor;
NCSTRING limit;
};
struct tyObject_FT_ListNodeRec_XDnyUdoyiWuZr1TEOohiUg {
tyObject_FT_ListNodeRec_XDnyUdoyiWuZr1TEOohiUg* prev;
tyObject_FT_ListNodeRec_XDnyUdoyiWuZr1TEOohiUg* next;
void* data;
};
struct tyObject_FT_Parameter_NjsbxXAfepI5sznbwCtdWQ {
unsigned long tag;
void* data;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(int, init_ZsVZnUmQTQMT9aW7rekNhYAfreetype)(void** lib);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(int, done_xIukrTHsoXKNLPh7iHLlkgfreetype)(void* lib);
static N_INLINE(int, newFace_k5U72fE5nSB9baKuZFDKfTAfreetype)(void* lib, NimStringDesc* filePathName, NI faceIndex, tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg** face);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(int, done_NTm1wxwatWEqXtddWEDYBAfreetype)(tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face);
static N_INLINE(int, setCharSize_9bEj7i9bJ1Efursli9cQ8p4Vwfreetype)(tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, long charWidth, long charHeight, unsigned int horzResolution, unsigned int vertResolution);
static N_INLINE(int, setPixelSizes_SGRQX7bZWwTO0F0jHY16BQfreetype)(tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned int pixelWidth, unsigned int pixelHeight);
static N_INLINE(int, loadGlyph_lfqu0Ztez0lin2514olIlwfreetype)(tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned int glyphIndex, NI32 loadFlags);
static N_INLINE(int, render_ctWPZHNZZ5QRB38zawBPuAfreetype)(tyObject_FT_GlyphSlotRec_vgLXoE6EShaOvQTaZaFq2A* slot, tyEnum_FT_Render_Mode_zO3P0oSmwPRTkSEHvaTJFA renderMode);
static N_INLINE(unsigned int, charIndex_uQHC6nJfpxkKGdW9bRxyF9cgfreetype)(tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned long charCode);
N_LIB_PRIVATE N_NIMCALL(NU32, FT_ENC_TAG_aoyAvLZGYxF4sv9ackBkDyw)(NI a, NI b, NI c, NI d);
N_LIB_PRIVATE N_NIMCALL(NU32, FT_ENC_TAG_ri9bQ6SecbNLAlZ4udok6Ig)(NIM_CHAR a, NIM_CHAR b, NIM_CHAR c, NIM_CHAR d);
static void* TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2;
tyProc_woTsLPew4uEvecZTma85ug Dl_138079_;
tyProc_Lgz6NmsDXnHcpuiE4Mnofw Dl_138083_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyProc_GsMkcMnC2p3jO231u2xjng Dl_138122_;
tyProc_myr4VYWQzqK31s8tKPHspw Dl_138129_;
tyProc_DgtznECvnzCE40vIqSeCWQ Dl_138137_;
tyProc_ip1VQmvVZva6M7hk4oS2rQ Dl_138145_;
tyProc_c2ePrv2WfeGvQJiUXzGj8A Dl_138149_;
tyProc_5UUS9c6EECHRvPK0JfqOaDA Dl_138154_;
tyProc_5UUS9c6EECHRvPK0JfqOaDA Dl_138157_;
tyProc_Sb9by7rnki9aXHiYgGxvvzoA Dl_138160_;
tyProc_vzcEEEjX0QSDl0Hf9azA6og Dl_138191_;
tyProc_QUVBw9auupGHuj883c8jszw Dl_138196_;
tyProc_Hhh1kJz9aJYAqt9brj9bU8evA Dl_138203_;
tyProc_8REO9a9aojbMu9aqLG8MMZTBg Dl_138208_;
tyProc_rXKjZ4cakpursqZhHL65mw Dl_138213_;
tyProc_43qV9cnGImy2biiipQGux9bg Dl_138498_;
tyProc_kdxNLzXijGA7NLYJ8H6EiQ Dl_138507_;
tyProc_qPJah9ccEBN5ljbSXRHZs8w Dl_138524_;
tyProc_KKai835y39cHt9cIAKaDLhbw Dl_138532_;
tyProc_8h04sZNlHwU3U2GI9b9blcag Dl_138539_;
tyProc_Ydtz0DlRkMf9au39ayRgQaGA Dl_138545_;
tyProc_lbtJj0Yy3OoP1cPce4aZXw Dl_138548_;
tyProc_b8FlAQWiP6TAcQHkSq6FYQ Dl_138552_;
tyProc_8z7TGAthLqF8peh9bDvcRdw Dl_138556_;
tyProc_SFXrLcuAryQrt53QAxf6CA Dl_138559_;
tyProc_9cFdZu4Ulq8Y9c0xmrV59cqYA Dl_138563_;
tyProc_RHggp9bPoWBt2cdsdTrKCww Dl_138568_;
tyProc_qs1D4ja0sYcYByaVwPLMOA Dl_138574_;
tyProc_kdmzsZNv6G6NyszL5PvnIw Dl_138593_;
tyProc_avUrQuqDb8NsLPqXsLm9b9bg Dl_138615_;
tyProc_Uib9b9cJuJKumeSvTrk3QENA Dl_138618_;
tyProc_FMXoHUjTcACA49akJeI9cTDw Dl_138623_;
tyProc_6cN6EpZdI0pK10qaMEd68g Dl_138628_;
tyProc_xcaajKr56FFuT3sInJCmQQ Dl_138632_;
tyProc_xcaajKr56FFuT3sInJCmQQ Dl_138637_;
tyProc_fy9aiiWKI4snQj1wug1ju7g Dl_138642_;
tyProc_MVmF0JW9bMI2YoeSQg5TZcg Dl_138647_;
tyProc_MVmF0JW9bMI2YoeSQg5TZcg Dl_138651_;
tyProc_iNFvlsSD7s5Un23DfeYhYw Dl_138655_;
tyProc_iNFvlsSD7s5Un23DfeYhYw Dl_138658_;
tyProc_iNFvlsSD7s5Un23DfeYhYw Dl_138661_;
tyProc_qVAMpBOv41Bn5QNpCEZcWg Dl_138664_;
tyProc_u9c7i818npb3ehaU36NHABQ Dl_138673_;
tyProc_YfiMDY6c7TQNpip0kwcGgw Dl_138682_;
tyProc_p3Rc9aHD2Ie9bCiqQpayUwuw Dl_138685_;
STRING_LITERAL(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_4, "libfreetype-6.dll", 17);
STRING_LITERAL(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_5, "libfreetype-6.dll", 17);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(int, init_ZsVZnUmQTQMT9aW7rekNhYAfreetype)(void** lib) {
	int result;
	nimfr_("init", "freetype.nim");
	result = (int)0;
	nimln_(243, "freetype.nim");
	result = Dl_138079_(lib);
	popFrame();
	return result;
}

static N_INLINE(int, done_xIukrTHsoXKNLPh7iHLlkgfreetype)(void* lib) {
	int result;
	nimfr_("done", "freetype.nim");
	result = (int)0;
	nimln_(246, "freetype.nim");
	result = Dl_138083_(lib);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(int, newFace_k5U72fE5nSB9baKuZFDKfTAfreetype)(void* lib, NimStringDesc* filePathName, NI faceIndex, tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg** face) {
	int result;
	nimfr_("newFace", "freetype.nim");
	result = (int)0;
	nimln_(291, "freetype.nim");
	result = Dl_138122_(lib, filePathName->data, ((long)chckRange(faceIndex, ((long) (-2147483647 -1)), ((long) 2147483647))), face);
	popFrame();
	return result;
}

static N_INLINE(int, done_NTm1wxwatWEqXtddWEDYBAfreetype)(tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face) {
	int result;
	nimfr_("done", "freetype.nim");
	result = (int)0;
	nimln_(294, "freetype.nim");
	result = Dl_138157_(face);
	popFrame();
	return result;
}

static N_INLINE(int, setCharSize_9bEj7i9bJ1Efursli9cQ8p4Vwfreetype)(tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, long charWidth, long charHeight, unsigned int horzResolution, unsigned int vertResolution) {
	int result;
	nimfr_("setCharSize", "freetype.nim");
	result = (int)0;
	nimln_(320, "freetype.nim");
	result = Dl_138196_(face, charWidth, charHeight, horzResolution, vertResolution);
	popFrame();
	return result;
}

static N_INLINE(int, setPixelSizes_SGRQX7bZWwTO0F0jHY16BQfreetype)(tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned int pixelWidth, unsigned int pixelHeight) {
	int result;
	nimfr_("setPixelSizes", "freetype.nim");
	result = (int)0;
	nimln_(324, "freetype.nim");
	result = Dl_138203_(face, pixelWidth, pixelHeight);
	popFrame();
	return result;
}

static N_INLINE(int, loadGlyph_lfqu0Ztez0lin2514olIlwfreetype)(tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned int glyphIndex, NI32 loadFlags) {
	int result;
	nimfr_("loadGlyph", "freetype.nim");
	result = (int)0;
	nimln_(327, "freetype.nim");
	result = Dl_138208_(face, glyphIndex, loadFlags);
	popFrame();
	return result;
}

static N_INLINE(int, render_ctWPZHNZZ5QRB38zawBPuAfreetype)(tyObject_FT_GlyphSlotRec_vgLXoE6EShaOvQTaZaFq2A* slot, tyEnum_FT_Render_Mode_zO3P0oSmwPRTkSEHvaTJFA renderMode) {
	int result;
	nimfr_("render", "freetype.nim");
	result = (int)0;
	nimln_(378, "freetype.nim");
	result = Dl_138507_(slot, renderMode);
	popFrame();
	return result;
}

static N_INLINE(unsigned int, charIndex_uQHC6nJfpxkKGdW9bRxyF9cgfreetype)(tyObject_FT_FaceRec_Bdl3bWUfZngY3GJHZTr9cvg* face, unsigned long charCode) {
	unsigned int result;
	nimfr_("charIndex", "freetype.nim");
	result = (unsigned int)0;
	nimln_(408, "freetype.nim");
	result = Dl_138559_(face, charCode);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU32, FT_ENC_TAG_aoyAvLZGYxF4sv9ackBkDyw)(NI a, NI b, NI c, NI d) {
	NU32 result;
	nimfr_("FT_ENC_TAG", "freetype.nim");
	result = (NU32)0;
	nimln_(15, "freetype.nim");
	nimln_(16, "freetype.nim");
	nimln_(15, "freetype.nim");
	nimln_(16, "freetype.nim");
	nimln_(17, "freetype.nim");
	result = (NU32)((NU32)((NU32)((NU32)((NU64)(((NU32) (a))) << (NU64)(((NI) 24))) | (NU32)((NU64)(((NU32) (b))) << (NU64)(((NI) 16)))) | (NU32)((NU64)(((NU32) (c))) << (NU64)(((NI) 8)))) | ((NU32) (d)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU32, FT_ENC_TAG_ri9bQ6SecbNLAlZ4udok6Ig)(NIM_CHAR a, NIM_CHAR b, NIM_CHAR c, NIM_CHAR d) {
	NU32 result;
	nimfr_("FT_ENC_TAG", "freetype.nim");
	result = (NU32)0;
	nimln_(15, "freetype.nim");
	nimln_(16, "freetype.nim");
	nimln_(15, "freetype.nim");
	nimln_(16, "freetype.nim");
	nimln_(17, "freetype.nim");
	result = (NU32)((NU32)((NU32)((NU32)((NU64)(((NU32) (((NU8)(a))))) << (NU64)(((NI) 24))) | (NU32)((NU64)(((NU32) (((NU8)(b))))) << (NU64)(((NI) 16)))) | (NU32)((NU64)(((NU32) (((NU8)(c))))) << (NU64)(((NI) 8)))) | ((NU32) (((NU8)(d)))));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, freetype_freetypeInit000)(void) {
	nimfr_("freetype", "freetype.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, freetype_freetypeDatInit000)(void) {
if (!((TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2 = nimLoadLibrary((NimStringDesc*) &TM_pb0q24Yi9b8Wmja9aY3i8qfQ_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_pb0q24Yi9b8Wmja9aY3i8qfQ_5);
	Dl_138079_ = (tyProc_woTsLPew4uEvecZTma85ug) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Init_FreeType");
	Dl_138083_ = (tyProc_Lgz6NmsDXnHcpuiE4Mnofw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Done_FreeType");
	Dl_138122_ = (tyProc_GsMkcMnC2p3jO231u2xjng) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_New_Face");
	Dl_138129_ = (tyProc_myr4VYWQzqK31s8tKPHspw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_New_Memory_Face");
	Dl_138137_ = (tyProc_DgtznECvnzCE40vIqSeCWQ) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Open_Face");
	Dl_138145_ = (tyProc_ip1VQmvVZva6M7hk4oS2rQ) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Attach_File");
	Dl_138149_ = (tyProc_c2ePrv2WfeGvQJiUXzGj8A) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Attach_Stream");
	Dl_138154_ = (tyProc_5UUS9c6EECHRvPK0JfqOaDA) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Reference_Face");
	Dl_138157_ = (tyProc_5UUS9c6EECHRvPK0JfqOaDA) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Done_Face");
	Dl_138160_ = (tyProc_Sb9by7rnki9aXHiYgGxvvzoA) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Select_Size");
	Dl_138191_ = (tyProc_vzcEEEjX0QSDl0Hf9azA6og) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Request_Size");
	Dl_138196_ = (tyProc_QUVBw9auupGHuj883c8jszw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Set_Char_Size");
	Dl_138203_ = (tyProc_Hhh1kJz9aJYAqt9brj9bU8evA) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Set_Pixel_Sizes");
	Dl_138208_ = (tyProc_8REO9a9aojbMu9aqLG8MMZTBg) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Load_Glyph");
	Dl_138213_ = (tyProc_rXKjZ4cakpursqZhHL65mw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Load_Char");
	Dl_138498_ = (tyProc_43qV9cnGImy2biiipQGux9bg) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Set_Transform");
	Dl_138507_ = (tyProc_kdxNLzXijGA7NLYJ8H6EiQ) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Render_Glyph");
	Dl_138524_ = (tyProc_qPJah9ccEBN5ljbSXRHZs8w) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_Kerning");
	Dl_138532_ = (tyProc_KKai835y39cHt9cIAKaDLhbw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_Track_Kerning");
	Dl_138539_ = (tyProc_8h04sZNlHwU3U2GI9b9blcag) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_Glyph_Name");
	Dl_138545_ = (tyProc_Ydtz0DlRkMf9au39ayRgQaGA) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_Postscript_Name");
	Dl_138548_ = (tyProc_lbtJj0Yy3OoP1cPce4aZXw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Select_Charmap");
	Dl_138552_ = (tyProc_b8FlAQWiP6TAcQHkSq6FYQ) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Set_Charmap");
	Dl_138556_ = (tyProc_8z7TGAthLqF8peh9bDvcRdw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_Charmap_Index");
	Dl_138559_ = (tyProc_SFXrLcuAryQrt53QAxf6CA) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_Char_Index");
	Dl_138563_ = (tyProc_9cFdZu4Ulq8Y9c0xmrV59cqYA) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_First_Char");
	Dl_138568_ = (tyProc_RHggp9bPoWBt2cdsdTrKCww) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_Next_Char");
	Dl_138574_ = (tyProc_qs1D4ja0sYcYByaVwPLMOA) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_Name_Index");
	Dl_138593_ = (tyProc_kdmzsZNv6G6NyszL5PvnIw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_SubGlyph_Info");
	Dl_138615_ = (tyProc_avUrQuqDb8NsLPqXsLm9b9bg) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Get_FSType_Flags");
	Dl_138618_ = (tyProc_Uib9b9cJuJKumeSvTrk3QENA) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Face_GetCharVariantIndex");
	Dl_138623_ = (tyProc_FMXoHUjTcACA49akJeI9cTDw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Face_GetCharVariantIsDefault");
	Dl_138628_ = (tyProc_6cN6EpZdI0pK10qaMEd68g) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Face_GetVariantSelectors");
	Dl_138632_ = (tyProc_xcaajKr56FFuT3sInJCmQQ) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Face_GetVariantsOfChar");
	Dl_138637_ = (tyProc_xcaajKr56FFuT3sInJCmQQ) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Face_GetCharsOfVariant");
	Dl_138642_ = (tyProc_fy9aiiWKI4snQj1wug1ju7g) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_MulDiv");
	Dl_138647_ = (tyProc_MVmF0JW9bMI2YoeSQg5TZcg) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_MulFix");
	Dl_138651_ = (tyProc_MVmF0JW9bMI2YoeSQg5TZcg) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_DivFix");
	Dl_138655_ = (tyProc_iNFvlsSD7s5Un23DfeYhYw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_RoundFix");
	Dl_138658_ = (tyProc_iNFvlsSD7s5Un23DfeYhYw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_CeilFix");
	Dl_138661_ = (tyProc_iNFvlsSD7s5Un23DfeYhYw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_FloorFix");
	Dl_138664_ = (tyProc_qVAMpBOv41Bn5QNpCEZcWg) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Vector_Transform");
	Dl_138673_ = (tyProc_u9c7i818npb3ehaU36NHABQ) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Library_Version");
	Dl_138682_ = (tyProc_YfiMDY6c7TQNpip0kwcGgw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Face_CheckTrueTypePatents");
	Dl_138685_ = (tyProc_p3Rc9aHD2Ie9bCiqQpayUwuw) nimGetProcAddr(TM_pb0q24Yi9b8Wmja9aY3i8qfQ_2, "FT_Face_SetUnpatentedHinting");
}

