/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files\mingw64-6.3.0\mingw64\bin\gcc.exe" -c  -w -mno-ms-bitfields  -IC:\nim-0.18.0\lib -o C:\Roguelike\src\fontprocs\nimcache\initrenderer.o C:\Roguelike\src\fontprocs\nimcache\initrenderer.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_mqgjJG1vbS44JnBjm1SPfQ tyTuple_mqgjJG1vbS44JnBjm1SPfQ;
typedef struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
typedef struct tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct tyTuple_mqgjJG1vbS44JnBjm1SPfQ {
tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* Field0;
tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* Field1;
};
typedef NI32 tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_fvOXafK39cW5YZA9b9bzinu9cw) (int flags);
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA {
  Exception Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CDECL_PTR(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w*, tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg*, tyProc_eGPD9aEHv9b8sVQMCQaPsYkg) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window, int index, int flags);
typedef N_CDECL_PTR(NIM_BOOL, tyProc_CS9bxA1KE4RHFQ1vMCkCBmg) (NCSTRING name, NCSTRING value);
typedef N_CDECL_PTR(int, tyProc_4hSZquf3VZZvlELaYshEWg) (int flags);
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_N8sad65Ws1y1PTmoH30cgg) (void);
struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w {
char dummy;
};
struct tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg {
char dummy;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyTuple_mqgjJG1vbS44JnBjm1SPfQ, initRenderer_jR75rxYI0iTrnhwMM7JB7A)(int screenWidth, int screenHeight);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, toBool_9bg9codirrpaPKZJuSwGJgEg)(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw some);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
extern tyProc_fvOXafK39cW5YZA9b9bzinu9cw Dl_146765_;
extern TNimType NTI_cogGoQVdHoYneQiFNLztxQ_;
extern TNimType NTI_pdGlehQiZtmAoj9apqLqmvA_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_147654_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg Dl_147356_;
extern tyProc_eGPD9aEHv9b8sVQMCQaPsYkg Dl_146811_;
extern tyProc_CS9bxA1KE4RHFQ1vMCkCBmg Dl_148013_;
extern tyProc_4hSZquf3VZZvlELaYshEWg Dl_151604_;
extern tyProc_N8sad65Ws1y1PTmoH30cgg Dl_149611_;
STRING_LITERAL(TM_9bKaNJPEFy3pvCWuXqAJS4w_2, "sdl2.init failed", 16);
STRING_LITERAL(TM_9bKaNJPEFy3pvCWuXqAJS4w_3, ", SDL error: ", 13);
STRING_LITERAL(TM_9bKaNJPEFy3pvCWuXqAJS4w_4, "createWindow failed", 19);
STRING_LITERAL(TM_9bKaNJPEFy3pvCWuXqAJS4w_5, "Renderer could not be created", 29);
STRING_LITERAL(TM_9bKaNJPEFy3pvCWuXqAJS4w_6, "SDL2 Image initialization failed", 32);
STRING_LITERAL(TM_9bKaNJPEFy3pvCWuXqAJS4w_7, "SDL2 TTF initialization failed", 30);

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_mqgjJG1vbS44JnBjm1SPfQ, initRenderer_jR75rxYI0iTrnhwMM7JB7A)(int screenWidth, int screenHeight) {
	tyTuple_mqgjJG1vbS44JnBjm1SPfQ result;
	tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window;
	tyObject_RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer;
	NIM_BOOL T24_;
	nimfr_("initRenderer", "initrenderer.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(9, "initrenderer.nim");
	{
		tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T3_;
		NIM_BOOL T4_;
		tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA* e;
		NimStringDesc* T7_;
		NCSTRING T8_;
		NimStringDesc* T9_;
		T3_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
		T3_ = Dl_146765_(((int) 65535));
		T4_ = (NIM_BOOL)0;
		T4_ = toBool_9bg9codirrpaPKZJuSwGJgEg(T3_);
		if (!!(T4_)) goto LA5_;
		e = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*) newObj((&NTI_cogGoQVdHoYneQiFNLztxQ_), sizeof(tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA));
		(*e).Sup.Sup.m_type = (&NTI_pdGlehQiZtmAoj9apqLqmvA_);
		nimln_(10, "initrenderer.nim");
		T7_ = (NimStringDesc*)0;
		nimln_(10, "errorhandling.nim");
		T8_ = (NCSTRING)0;
		T8_ = Dl_147654_();
		T9_ = (NimStringDesc*)0;
		T9_ = cstrToNimstr(T8_);
		T7_ = rawNewString(((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_2)->Sup.len + T9_->Sup.len + 13);
appendString(T7_, ((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_2));
appendString(T7_, ((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_3));
appendString(T7_, T9_);
		asgnRefNoCycle((void**) (&(*e).Sup.message), T7_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(10, "errorhandling.nim");
		raiseException((Exception*)e, "SDLException");
	}
	LA5_: ;
	nimln_(12, "initrenderer.nim");
	window = Dl_147356_("SpaceRL", ((int) 100), ((int) 100), screenWidth, screenHeight, ((unsigned int) 4));
	nimln_(13, "initrenderer.nim");
	{
		tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA* e_2;
		NimStringDesc* T14_;
		NCSTRING T15_;
		NimStringDesc* T16_;
		if (!(window == 0)) goto LA12_;
		e_2 = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*)0;
		nimln_(2811, "system.nim");
		e_2 = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*) newObj((&NTI_cogGoQVdHoYneQiFNLztxQ_), sizeof(tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA));
		(*e_2).Sup.Sup.m_type = (&NTI_pdGlehQiZtmAoj9apqLqmvA_);
		nimln_(14, "initrenderer.nim");
		T14_ = (NimStringDesc*)0;
		nimln_(10, "errorhandling.nim");
		T15_ = (NCSTRING)0;
		T15_ = Dl_147654_();
		T16_ = (NimStringDesc*)0;
		T16_ = cstrToNimstr(T15_);
		T14_ = rawNewString(((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_4)->Sup.len + T16_->Sup.len + 13);
appendString(T14_, ((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_4));
appendString(T14_, ((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_3));
appendString(T14_, T16_);
		asgnRefNoCycle((void**) (&(*e_2).Sup.message), T14_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
		nimln_(10, "errorhandling.nim");
		raiseException((Exception*)e_2, "SDLException");
	}
	LA12_: ;
	nimln_(16, "initrenderer.nim");
	renderer = Dl_146811_(window, ((int) -1), ((NI32) 6));
	nimln_(18, "initrenderer.nim");
	{
		tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA* e_3;
		NimStringDesc* T21_;
		NCSTRING T22_;
		NimStringDesc* T23_;
		if (!(renderer == 0)) goto LA19_;
		e_3 = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*)0;
		nimln_(2811, "system.nim");
		e_3 = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*) newObj((&NTI_cogGoQVdHoYneQiFNLztxQ_), sizeof(tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA));
		(*e_3).Sup.Sup.m_type = (&NTI_pdGlehQiZtmAoj9apqLqmvA_);
		nimln_(18, "initrenderer.nim");
		T21_ = (NimStringDesc*)0;
		nimln_(10, "errorhandling.nim");
		T22_ = (NCSTRING)0;
		T22_ = Dl_147654_();
		T23_ = (NimStringDesc*)0;
		T23_ = cstrToNimstr(T22_);
		T21_ = rawNewString(((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_5)->Sup.len + T23_->Sup.len + 13);
appendString(T21_, ((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_5));
appendString(T21_, ((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_3));
appendString(T21_, T23_);
		asgnRefNoCycle((void**) (&(*e_3).Sup.message), T21_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e_3).Sup.parent), NIM_NIL);
		nimln_(10, "errorhandling.nim");
		raiseException((Exception*)e_3, "SDLException");
	}
	LA19_: ;
	nimln_(19, "initrenderer.nim");
	T24_ = (NIM_BOOL)0;
	T24_ = Dl_148013_("SDL_HINT_RENDER_SCALE_QUALITY", "1");
	T24_;
	nimln_(21, "initrenderer.nim");
	{
		int T27_;
		tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA* e_4;
		NimStringDesc* T30_;
		NCSTRING T31_;
		NimStringDesc* T32_;
		nimln_(398, "system.nim");
		nimln_(21, "initrenderer.nim");
		T27_ = (int)0;
		T27_ = Dl_151604_(((int) 2));
		if (!!((T27_ == ((NI32) 2)))) goto LA28_;
		e_4 = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*)0;
		nimln_(2811, "system.nim");
		e_4 = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*) newObj((&NTI_cogGoQVdHoYneQiFNLztxQ_), sizeof(tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA));
		(*e_4).Sup.Sup.m_type = (&NTI_pdGlehQiZtmAoj9apqLqmvA_);
		nimln_(22, "initrenderer.nim");
		T30_ = (NimStringDesc*)0;
		nimln_(10, "errorhandling.nim");
		T31_ = (NCSTRING)0;
		T31_ = Dl_147654_();
		T32_ = (NimStringDesc*)0;
		T32_ = cstrToNimstr(T31_);
		T30_ = rawNewString(((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_6)->Sup.len + T32_->Sup.len + 13);
appendString(T30_, ((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_6));
appendString(T30_, ((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_3));
appendString(T30_, T32_);
		asgnRefNoCycle((void**) (&(*e_4).Sup.message), T30_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e_4).Sup.parent), NIM_NIL);
		nimln_(10, "errorhandling.nim");
		raiseException((Exception*)e_4, "SDLException");
	}
	LA28_: ;
	nimln_(25, "initrenderer.nim");
	{
		tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T35_;
		tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA* e_5;
		NimStringDesc* T38_;
		NCSTRING T39_;
		NimStringDesc* T40_;
		T35_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
		T35_ = Dl_149611_();
		if (!(T35_ == ((tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw) -1))) goto LA36_;
		e_5 = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*)0;
		nimln_(2811, "system.nim");
		e_5 = (tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA*) newObj((&NTI_cogGoQVdHoYneQiFNLztxQ_), sizeof(tyObject_SDLException_pdGlehQiZtmAoj9apqLqmvA));
		(*e_5).Sup.Sup.m_type = (&NTI_pdGlehQiZtmAoj9apqLqmvA_);
		nimln_(25, "initrenderer.nim");
		T38_ = (NimStringDesc*)0;
		nimln_(10, "errorhandling.nim");
		T39_ = (NCSTRING)0;
		T39_ = Dl_147654_();
		T40_ = (NimStringDesc*)0;
		T40_ = cstrToNimstr(T39_);
		T38_ = rawNewString(((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_7)->Sup.len + T40_->Sup.len + 13);
appendString(T38_, ((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_7));
appendString(T38_, ((NimStringDesc*) &TM_9bKaNJPEFy3pvCWuXqAJS4w_3));
appendString(T38_, T40_);
		asgnRefNoCycle((void**) (&(*e_5).Sup.message), T38_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e_5).Sup.parent), NIM_NIL);
		nimln_(10, "errorhandling.nim");
		raiseException((Exception*)e_5, "SDLException");
	}
	LA36_: ;
	nimln_(27, "initrenderer.nim");
	result.Field0 = window;
	result.Field1 = renderer;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_initrendererInit000)(void) {
	nimfr_("initrenderer", "initrenderer.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_initrendererDatInit000)(void) {
}

